### ISSUE TITLE
[api] getHistroy not return the true answer

### ISSUE THREAD

**Issue by cugxuan** [PointStoneTeam/cugsync#3]
getHistory 接口没有返回正常的结果

http://localhost:8000/getHistory?name=ubuntu 返回是 ubuntu-release 的内容，情况如图

![image](https://user-images.githubusercontent.com/23120372/83716351-3be39d80-a662-11ea-85c9-98199a85890f.png)

**Comment by chenlx0** [comment]
fixed in https://github.com/PointStoneTeam/cugsync/commit/b8f58d53c29f54a0cf3f3f098cff7c2cd7829b13

**Comment by cugxuan** [comment]
😇
